// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "./add_jquery"
import * as bootstrap from "bootstrap"
// import "popper"
// import "activestorage"
// import "bootstrap"
// import "jquery-ui"
import "./controllers"
import "@rails/actioncable" 
import "./channels"
// import { popper } from "@popperjs/core"
// import "./cable"
// import * as bootstrap from "bootstrap"

